package com.github.jomof.dap.integration

import com.github.jomof.dap.client.DapClient
import com.github.jomof.dap.client.DapEvent
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.takeWhile
import kotlinx.coroutines.future.await
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.eclipse.lsp4j.debug.InitializeRequestArguments
import org.junit.After
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Before
import org.junit.Test
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.time.Duration.Companion.seconds

/**
 * CodeLLDB twin of [LldbDapNoDebugRunIntegrationTest]: end-to-end
 * `initialize → launch(noDebug=true) → configurationDone` against a
 * tiny C smoke binary, asserting program stdout flows back as DAP
 * `output` events.
 *
 * Why this exists separately from the lldb-dap test: CodeLLDB has its
 * own forwarding code path (it adds a `category=stdout` field, while
 * lldb-dap uses `category=console` historically). Both should still
 * surface output via the same DAP `Output` event shape — this test
 * pins that behaviour so future refactors of `DapEvent.Output` don't
 * accidentally drop one side.
 *
 * Skipped unless `DAP_INTEGRATION_TESTS=1` is set AND the smoke binary
 * has been built (`bash src/test/resources/fixtures/c/build.sh`).
 */
class CodeLldbNoDebugRunIntegrationTest {

    private var fixture: CodeLldbProcessFixture? = null
    private var client: DapClient? = null

    @Before fun setUp() {
        assumeTrue("Set DAP_INTEGRATION_TESTS=1 to enable", System.getenv("DAP_INTEGRATION_TESTS") == "1")
        assumeTrue(
            "smoke binary not built — run src/test/resources/fixtures/c/build.sh",
            Files.isExecutable(SMOKE_BINARY),
        )
        fixture = CodeLldbTestFixtures.tryProvisionAndSpawn()
        assumeTrue("CodeLLDB could not be provisioned on this host", fixture != null)
    }

    @After fun tearDown() {
        client?.dispose()
        fixture?.dispose()
    }

    @Test fun `codelldb noDebug launches binary and forwards stdout`() = runBlocking {
        val fx = fixture!!
        val client = DapClient(fx.transport).also { it.connect() }
        this@CodeLldbNoDebugRunIntegrationTest.client = client

        val eventTrace = java.util.concurrent.CopyOnWriteArrayList<String>()
        val collected = StringBuilder()
        coroutineScope {
            val outputJob = async {
                withTimeout(20.seconds) {
                    client.events
                        .onEach { event ->
                            eventTrace += event::class.simpleName ?: "?"
                            if (event is DapEvent.Output) {
                                event.payload.output?.let { synchronized(collected) { collected.append(it) } }
                            }
                        }
                        .takeWhile { event ->
                            event !is DapEvent.Terminated && event !is DapEvent.Exited &&
                                !synchronized(collected) { collected.toString() }.contains(EXPECTED_OUTPUT)
                        }
                        .collect { /* drained for side effects above */ }
                }
                synchronized(collected) { collected.toString() }
            }

            launch {
                withTimeout(20.seconds) {
                    val capabilities = client.initialize(InitializeRequestArguments().apply {
                        clientID = "dap.intellij.integration-test"
                        clientName = "IntelliJ DAP (CodeLLDB Run integration test)"
                        adapterID = "lldb"
                        pathFormat = "path"
                        linesStartAt1 = true
                        columnsStartAt1 = true
                        supportsRunInTerminalRequest = true
                    })
                    val launchArgs = mapOf<String, Any>(
                        // CodeLLDB's `launch` accepts the same `program`/
                        // `noDebug` shape as lldb-dap (its launch.json is
                        // generated by lsp4ij with these exact keys).
                        "program" to SMOKE_BINARY.toString(),
                        "noDebug" to true,
                    )
                    val launchAck = client.launch(launchArgs)
                    client.awaitInitialized()
                    if (capabilities.supportsConfigurationDoneRequest) {
                        client.configurationDone()
                    }
                    launchAck.await()
                }
            }

            val captured = outputJob.await()
            assertTrue(
                "Expected CodeLLDB to forward program stdout containing \"$EXPECTED_OUTPUT\". " +
                    "Events: $eventTrace. Collected output: <<<$captured>>>",
                captured.contains(EXPECTED_OUTPUT),
            )
        }
    }

    private companion object {
        const val EXPECTED_OUTPUT = "hello from dap test"
        val SMOKE_BINARY: Path = Paths.get(
            System.getProperty("user.dir"),
            "src",
            "test",
            "resources",
            "fixtures",
            "c",
            "hello",
        )
    }
}
